# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/users/BenMillward/Desktop/Complete_setup/cfg/clocks.xdc

# XDC: C:/users/BenMillward/Desktop/Complete_setup/cfg/ports.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ds_buf_1_0 || ORIG_REF_NAME==system_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_2_0/system_util_ds_buf_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ds_buf_2_0 || ORIG_REF_NAME==system_util_ds_buf_2_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_red_pitaya_adc_0_0/system_axis_red_pitaya_adc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_adc_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_adc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_1/system_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_1 || ORIG_REF_NAME==system_processing_system7_0_1} -quiet] -quiet

# IP: bd/system/ip/system_Scan_0_1/system_Scan_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Scan_0_1 || ORIG_REF_NAME==system_Scan_0_1} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_50M_1/system_rst_ps7_0_50M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_50M_1 || ORIG_REF_NAME==system_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_7/system_axi_gpio_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_7 || ORIG_REF_NAME==system_axi_gpio_0_7} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_8/system_axi_gpio_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_8 || ORIG_REF_NAME==system_axi_gpio_0_8} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_1_5/system_axi_gpio_1_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_5 || ORIG_REF_NAME==system_axi_gpio_1_5} -quiet] -quiet

# IP: bd/system/ip/system_xbar_4/system_xbar_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_4 || ORIG_REF_NAME==system_xbar_4} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_4/system_ps7_0_axi_periph_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_4 || ORIG_REF_NAME==system_ps7_0_axi_periph_4} -quiet] -quiet

# IP: bd/system/ip/system_Ramp_0_0/system_Ramp_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Ramp_0_0 || ORIG_REF_NAME==system_Ramp_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_3_0 || ORIG_REF_NAME==system_axi_gpio_3_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_3_1/system_axi_gpio_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_3_1 || ORIG_REF_NAME==system_axi_gpio_3_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_3_2/system_axi_gpio_3_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_3_2 || ORIG_REF_NAME==system_axi_gpio_3_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_4_0/system_axi_gpio_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_4_0 || ORIG_REF_NAME==system_axi_gpio_4_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_3_3/system_axi_gpio_3_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_3_3 || ORIG_REF_NAME==system_axi_gpio_3_3} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_3_4/system_axi_gpio_3_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_3_4 || ORIG_REF_NAME==system_axi_gpio_3_4} -quiet] -quiet

# IP: bd/system/ip/system_axis_red_pitaya_dac_0_0/system_axis_red_pitaya_dac_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_dac_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_dac_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_10_0/system_axi_gpio_10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_10_0 || ORIG_REF_NAME==system_axi_gpio_10_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/BenMillward/Desktop/Complete_setup/tmp/Scan_Hold_test/Scan_Hold_test.gen/sources_1/bd/system/system_ooc.xdc
