# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/BenMillward/Desktop/Complete_setup/tmp/PID_HOLD_VOLTS/PID_HOLD_VOLTS.srcs/sources_1/bd/system/ip/system_axi_gpio_1_3/system_axi_gpio_1_3.xci
# IP: The module: 'system_axi_gpio_1_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/BenMillward/Desktop/Complete_setup/tmp/PID_HOLD_VOLTS/PID_HOLD_VOLTS.gen/sources_1/bd/system/ip/system_axi_gpio_1_3/system_axi_gpio_1_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_1_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/BenMillward/Desktop/Complete_setup/tmp/PID_HOLD_VOLTS/PID_HOLD_VOLTS.gen/sources_1/bd/system/ip/system_axi_gpio_1_3/system_axi_gpio_1_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_1_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/BenMillward/Desktop/Complete_setup/tmp/PID_HOLD_VOLTS/PID_HOLD_VOLTS.gen/sources_1/bd/system/ip/system_axi_gpio_1_3/system_axi_gpio_1_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_1_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/BenMillward/Desktop/Complete_setup/tmp/PID_HOLD_VOLTS/PID_HOLD_VOLTS.srcs/sources_1/bd/system/ip/system_axi_gpio_1_3/system_axi_gpio_1_3.xci
# IP: The module: 'system_axi_gpio_1_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/BenMillward/Desktop/Complete_setup/tmp/PID_HOLD_VOLTS/PID_HOLD_VOLTS.gen/sources_1/bd/system/ip/system_axi_gpio_1_3/system_axi_gpio_1_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_1_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/BenMillward/Desktop/Complete_setup/tmp/PID_HOLD_VOLTS/PID_HOLD_VOLTS.gen/sources_1/bd/system/ip/system_axi_gpio_1_3/system_axi_gpio_1_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_1_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/BenMillward/Desktop/Complete_setup/tmp/PID_HOLD_VOLTS/PID_HOLD_VOLTS.gen/sources_1/bd/system/ip/system_axi_gpio_1_3/system_axi_gpio_1_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_1_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
