# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/users/BenMillward/Desktop/Complete_setup/cfg/clocks.xdc

# XDC: C:/users/BenMillward/Desktop/Complete_setup/cfg/ports.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ds_buf_1_0 || ORIG_REF_NAME==system_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_2_0/system_util_ds_buf_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ds_buf_2_0 || ORIG_REF_NAME==system_util_ds_buf_2_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_red_pitaya_dac_0_0/system_axis_red_pitaya_dac_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_dac_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_dac_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_red_pitaya_adc_0_0/system_axis_red_pitaya_adc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_adc_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_adc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_low_pass_0_0/system_low_pass_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_low_pass_0_0 || ORIG_REF_NAME==system_low_pass_0_0} -quiet] -quiet

# IP: bd/system/ip/system_scale_0_0/system_scale_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_scale_0_0 || ORIG_REF_NAME==system_scale_0_0} -quiet] -quiet

# IP: bd/system/ip/system_divider_0_0/system_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_divider_0_0 || ORIG_REF_NAME==system_divider_0_0} -quiet] -quiet

# IP: bd/system/ip/system_signal_split_0_1/system_signal_split_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_signal_split_0_1 || ORIG_REF_NAME==system_signal_split_0_1} -quiet] -quiet

# IP: bd/system/ip/system_signal_split_2_0_0/system_signal_split_2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_signal_split_2_0_0 || ORIG_REF_NAME==system_signal_split_2_0_0} -quiet] -quiet

# IP: bd/system/ip/system_Add_0_0/system_Add_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Add_0_0 || ORIG_REF_NAME==system_Add_0_0} -quiet] -quiet

# IP: bd/system/ip/system_LED_Contoller_0_1/system_LED_Contoller_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_LED_Contoller_0_1 || ORIG_REF_NAME==system_LED_Contoller_0_1} -quiet] -quiet

# IP: bd/system/ip/system_PI_ctrl_0_1/system_PI_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_PI_ctrl_0_1 || ORIG_REF_NAME==system_PI_ctrl_0_1} -quiet] -quiet

# IP: bd/system/ip/system_Selector_0_1/system_Selector_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Selector_0_1 || ORIG_REF_NAME==system_Selector_0_1} -quiet] -quiet

# IP: bd/system/ip/system_Scan_0_1/system_Scan_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Scan_0_1 || ORIG_REF_NAME==system_Scan_0_1} -quiet] -quiet

# IP: bd/system/ip/system_Voltage_Holder_0_4/system_Voltage_Holder_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Voltage_Holder_0_4 || ORIG_REF_NAME==system_Voltage_Holder_0_4} -quiet] -quiet

# IP: bd/system/ip/system_Voltage_Holder_1_0/system_Voltage_Holder_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Voltage_Holder_1_0 || ORIG_REF_NAME==system_Voltage_Holder_1_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_1_3/system_axi_gpio_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_3 || ORIG_REF_NAME==system_axi_gpio_1_3} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_6_0/system_axi_gpio_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_6_0 || ORIG_REF_NAME==system_axi_gpio_6_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_6_1/system_axi_gpio_6_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_6_1 || ORIG_REF_NAME==system_axi_gpio_6_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_9_0/system_axi_gpio_9_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_9_0 || ORIG_REF_NAME==system_axi_gpio_9_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_1 || ORIG_REF_NAME==system_axi_gpio_0_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_2/system_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_2 || ORIG_REF_NAME==system_axi_gpio_0_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_3/system_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_3 || ORIG_REF_NAME==system_axi_gpio_0_3} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_4/system_axi_gpio_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_4 || ORIG_REF_NAME==system_axi_gpio_0_4} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_1_1/system_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_1 || ORIG_REF_NAME==system_axi_gpio_1_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_7_1/system_axi_gpio_7_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_7_1 || ORIG_REF_NAME==system_axi_gpio_7_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_1_2/system_axi_gpio_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_2 || ORIG_REF_NAME==system_axi_gpio_1_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_11_0/system_axi_gpio_11_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_11_0 || ORIG_REF_NAME==system_axi_gpio_11_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_1/system_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_1/system_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_1 || ORIG_REF_NAME==system_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_1/system_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_1 || ORIG_REF_NAME==system_processing_system7_0_1} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_50M_1/system_rst_ps7_0_50M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_50M_1 || ORIG_REF_NAME==system_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/system/ip/system_Hivemind_0_1/system_Hivemind_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Hivemind_0_1 || ORIG_REF_NAME==system_Hivemind_0_1} -quiet] -quiet

# IP: bd/system/ip/system_Ramp_0_1/system_Ramp_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Ramp_0_1 || ORIG_REF_NAME==system_Ramp_0_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/BenMillward/Desktop/Complete_setup/tmp/PID_2/PID_2.gen/sources_1/bd/system/system_ooc.xdc
