# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/BenMillward/Desktop/Complete_setup/tmp/Scan_Hold_test/Scan_Hold_test.srcs/sources_1/bd/system/ip/system_xbar_4/system_xbar_4.xci
# IP: The module: 'system_xbar_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/BenMillward/Desktop/Complete_setup/tmp/Scan_Hold_test/Scan_Hold_test.gen/sources_1/bd/system/ip/system_xbar_4/system_xbar_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xbar_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/BenMillward/Desktop/Complete_setup/tmp/Scan_Hold_test/Scan_Hold_test.srcs/sources_1/bd/system/ip/system_xbar_4/system_xbar_4.xci
# IP: The module: 'system_xbar_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/BenMillward/Desktop/Complete_setup/tmp/Scan_Hold_test/Scan_Hold_test.gen/sources_1/bd/system/ip/system_xbar_4/system_xbar_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xbar_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
